<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

<!-- This file is automatically generated. Don't edit it. -->


<xsl:template match="*">
  <xsl:call-template name="attr_handler"/>
</xsl:template>

<xsl:template name="attr_handler">
  <xsl:choose>
<!--  <xsl:when test="($show_mor_info_flag and (./@mph or ./@sem)) or ./@id -->
  <xsl:when test="./@id or ./@mph or ./@sem
or ./@eq
or ./@eq.mt
or ./@eq.ab
or ./@eq.in
or ./@eq.sit
or ./@eq.met
or ./@sce
or ./@pco
or ./@arg
or ./@arg.sloppy
or ./@arg.rpt
or ./@arg.rpc
or ./@arg.in
or ./@mod
or ./@sbj
or ./@obj
or ./@obj.rcp
or ./@obj.in
or ./@obj.sup
or ./@obj.rpt
or ./@obj.msr
or ./@obj.met
or ./@obj.loc
or ./@obj.ql
or ./@obj.mt
or ./@obj.loc.msr
or ./@obj.ctl
or ./@iob
or ./@iob.in
or ./@ctl.obj
or ./@ctl.iob
or ./@ctl.agt
or ./@ctl.gol
or ./@ctl.src
or ./@ctl.exp
or ./@ctl.res
or ./@ctl.cap
or ./@ctl.aen
or ./@ctl.smr
or ./@ctl.res.mt
or ./@ctl.pbj
or ./@ctl.obl
or ./@ctl.obj.rcp
or ./@ctl.ioc
or ./@ctl.ilb
or ./@ctl.cnt
or ./@ctl.agt.rpt
or ./@plg
or ./@agt
or ./@agt.rcp
or ./@agt.rpt
or ./@agt.sit
or ./@agt.sub
or ./@agt.sup
or ./@agt.spt
or ./@agt.msr
or ./@agt.met
or ./@agt.jnt
or ./@agt.in
or ./@cap
or ./@aen
or ./@aen.rcp
or ./@aen.sub
or ./@rpt
or ./@src
or ./@src.loc
or ./@gol
or ./@gol.ilc
or ./@gol.obj
or ./@gol.loc
or ./@gol.sit
or ./@res
or ./@res.mt
or ./@res.msr
or ./@mat
or ./@ben
or ./@exp
or ./@exp.rpt
or ./@exp.rcp
or ./@exp.met
or ./@jnt
or ./@pos
or ./@ela
or ./@eg
or ./@cnt
or ./@tnc
or ./@cau
or ./@pur
or ./@cnd
or ./@sub
or ./@sup
or ./@sup.mt
or ./@tmx
or ./@tmx.mob
or ./@tim
or ./@spx
or ./@spx.sup
or ./@spx.sub
or ./@spx.mob
or ./@loc
or ./@ilc
or ./@ilc.gol
or ./@via
or ./@dir
or ./@opp
or ./@int
or ./@fin
or ./@stx.mob
or ./@sit
or ./@sit.sup
or ./@txx.sub
or ./@in
or ./@in.sloppy
or ./@ni
or ./@ccm
or ./@met
or ./@cmp
or ./@sim
or ./@bas
or ./@cev
or ./@who
or ./@whm
or ./@mns
or ./@mns.sup
or ./@msr
or ./@mob
or ./@mob.in
or ./@ql
or ./@sbm
or ./@sbm.sloppy
or ./@sbm.mt
or ./@uni
or ./@mkr
or ./@adr
or ./@age
or ./@utr
or ./@smr
or ./@otr
">
    <xsl:element name="span">
      <!-- id属性を表示 -->
      <xsl:if test="./@id">
	<xsl:attribute name="id"><xsl:value-of select="./@id"/></xsl:attribute>
      </xsl:if>
      <!-- class属性を表示(値は元の属性と組を全て連結した文字列) -->
<!--  <xsl:if test="($show_mor_info_flag and (./@mph or ./@sem)) -->
      <xsl:if test="./@mph or ./@sem
or ./@eq
or ./@eq.mt
or ./@eq.ab
or ./@eq.in
or ./@eq.sit
or ./@eq.met
or ./@sce
or ./@pco
or ./@arg
or ./@arg.sloppy
or ./@arg.rpt
or ./@arg.rpc
or ./@arg.in
or ./@mod
or ./@sbj
or ./@obj
or ./@obj.rcp
or ./@obj.in
or ./@obj.sup
or ./@obj.rpt
or ./@obj.msr
or ./@obj.met
or ./@obj.loc
or ./@obj.ql
or ./@obj.mt
or ./@obj.loc.msr
or ./@obj.ctl
or ./@iob
or ./@iob.in
or ./@ctl.obj
or ./@ctl.iob
or ./@ctl.agt
or ./@ctl.gol
or ./@ctl.src
or ./@ctl.exp
or ./@ctl.res
or ./@ctl.cap
or ./@ctl.aen
or ./@ctl.smr
or ./@ctl.res.mt
or ./@ctl.pbj
or ./@ctl.obl
or ./@ctl.obj.rcp
or ./@ctl.ioc
or ./@ctl.ilb
or ./@ctl.cnt
or ./@ctl.agt.rpt
or ./@plg
or ./@agt
or ./@agt.rcp
or ./@agt.rpt
or ./@agt.sit
or ./@agt.sub
or ./@agt.sup
or ./@agt.spt
or ./@agt.msr
or ./@agt.met
or ./@agt.jnt
or ./@agt.in
or ./@cap
or ./@aen
or ./@aen.rcp
or ./@aen.sub
or ./@rpt
or ./@src
or ./@src.loc
or ./@gol
or ./@gol.ilc
or ./@gol.obj
or ./@gol.loc
or ./@gol.sit
or ./@res
or ./@res.mt
or ./@res.msr
or ./@mat
or ./@ben
or ./@exp
or ./@exp.rpt
or ./@exp.rcp
or ./@exp.met
or ./@jnt
or ./@pos
or ./@ela
or ./@eg
or ./@cnt
or ./@tnc
or ./@cau
or ./@pur
or ./@cnd
or ./@sub
or ./@sup
or ./@sup.mt
or ./@tmx
or ./@tmx.mob
or ./@tim
or ./@spx
or ./@spx.sup
or ./@spx.sub
or ./@spx.mob
or ./@loc
or ./@ilc
or ./@ilc.gol
or ./@via
or ./@dir
or ./@opp
or ./@int
or ./@fin
or ./@stx.mob
or ./@sit
or ./@sit.sup
or ./@txx.sub
or ./@in
or ./@in.sloppy
or ./@ni
or ./@ccm
or ./@met
or ./@cmp
or ./@sim
or ./@bas
or ./@cev
or ./@who
or ./@whm
or ./@mns
or ./@mns.sup
or ./@msr
or ./@mob
or ./@mob.in
or ./@ql
or ./@sbm
or ./@sbm.sloppy
or ./@sbm.mt
or ./@uni
or ./@mkr
or ./@adr
or ./@age
or ./@utr
or ./@smr
or ./@otr
">
	<xsl:attribute name="class">
	  <xsl:call-template name="make_attr_list"/>
	</xsl:attribute>
      </xsl:if>
      <!-- 形態素情報を表示するための JavaScript コードを表示 -->
      <!-- <xsl:if test="$show_mor_info_flag"> -->
	<xsl:if test="./@mph or ./@sem">
	  <xsl:attribute name="onmouseup">
	    <xsl:text>ck1(event)</xsl:text>
	  </xsl:attribute>
	  <!--
	  <xsl:attribute name="style">
	    <xsl:text>white-space:nowrap;</xsl:text>
	  </xsl:attribute>
	  -->
	</xsl:if>
      <!-- </xsl:if> -->
      <xsl:choose>
      <!-- eq属性を表わすマーク(●)を表示 -->
      <xsl:when test="false()
or ./@eq
or ./@eq.mt
or ./@eq.ab
or ./@eq.in
or ./@eq.sit
or ./@eq.met
">
	<span class="marker_eq" onmouseup="ck2(this)">●</span>
      </xsl:when>
      <!-- id属性を表わすマーク(■)を表示
	   id="ID-..." のときは文のIDなので表示しない -->
      <xsl:when test="./@id and not(starts-with(./@id,'ID-'))">
	<span class="marker_id" onmouseup="ck2(this)">■</span>
      </xsl:when>
      </xsl:choose>
      <!-- 関係の属性を表わすマーク(▼)を表示 -->
      <xsl:if test="false()
or ./@sce
or ./@pco
or ./@arg
or ./@arg.sloppy
or ./@arg.rpt
or ./@arg.rpc
or ./@arg.in
or ./@mod
or ./@sbj
or ./@obj
or ./@obj.rcp
or ./@obj.in
or ./@obj.sup
or ./@obj.rpt
or ./@obj.msr
or ./@obj.met
or ./@obj.loc
or ./@obj.ql
or ./@obj.mt
or ./@obj.loc.msr
or ./@obj.ctl
or ./@iob
or ./@iob.in
or ./@ctl.obj
or ./@ctl.iob
or ./@ctl.agt
or ./@ctl.gol
or ./@ctl.src
or ./@ctl.exp
or ./@ctl.res
or ./@ctl.cap
or ./@ctl.aen
or ./@ctl.smr
or ./@ctl.res.mt
or ./@ctl.pbj
or ./@ctl.obl
or ./@ctl.obj.rcp
or ./@ctl.ioc
or ./@ctl.ilb
or ./@ctl.cnt
or ./@ctl.agt.rpt
or ./@plg
or ./@agt
or ./@agt.rcp
or ./@agt.rpt
or ./@agt.sit
or ./@agt.sub
or ./@agt.sup
or ./@agt.spt
or ./@agt.msr
or ./@agt.met
or ./@agt.jnt
or ./@agt.in
or ./@cap
or ./@aen
or ./@aen.rcp
or ./@aen.sub
or ./@rpt
or ./@src
or ./@src.loc
or ./@gol
or ./@gol.ilc
or ./@gol.obj
or ./@gol.loc
or ./@gol.sit
or ./@res
or ./@res.mt
or ./@res.msr
or ./@mat
or ./@ben
or ./@exp
or ./@exp.rpt
or ./@exp.rcp
or ./@exp.met
or ./@jnt
or ./@pos
or ./@ela
or ./@eg
or ./@cnt
or ./@tnc
or ./@cau
or ./@pur
or ./@cnd
or ./@sub
or ./@sup
or ./@sup.mt
or ./@tmx
or ./@tmx.mob
or ./@tim
or ./@spx
or ./@spx.sup
or ./@spx.sub
or ./@spx.mob
or ./@loc
or ./@ilc
or ./@ilc.gol
or ./@via
or ./@dir
or ./@opp
or ./@int
or ./@fin
or ./@stx.mob
or ./@sit
or ./@sit.sup
or ./@txx.sub
or ./@in
or ./@in.sloppy
or ./@ni
or ./@ccm
or ./@met
or ./@cmp
or ./@sim
or ./@bas
or ./@cev
or ./@who
or ./@whm
or ./@mns
or ./@mns.sup
or ./@msr
or ./@mob
or ./@mob.in
or ./@ql
or ./@sbm
or ./@sbm.sloppy
or ./@sbm.mt
or ./@uni
or ./@mkr
or ./@adr
or ./@age
or ./@utr
or ./@smr
or ./@otr
">
	<span class="marker_rel" onmouseup="ck3(event)">▼</span>
      </xsl:if>
      <xsl:apply-templates />
    </xsl:element>
  </xsl:when>
  <xsl:otherwise>
    <xsl:apply-templates />
  </xsl:otherwise>
  </xsl:choose>
</xsl:template>

<xsl:template name="make_attr_list">
  <xsl:for-each select="./@*">
<!-- <xsl:if test="($show_mor_info_flag and (name(.) = 'mph' or name(.) = 'sem')) -->
    <xsl:if test="name(.) = 'mph' or name(.) = 'sem'
or name(.) = 'eq'
or name(.) = 'eq.mt'
or name(.) = 'eq.ab'
or name(.) = 'eq.in'
or name(.) = 'eq.sit'
or name(.) = 'eq.met'
or name(.) = 'sce'
or name(.) = 'pco'
or name(.) = 'arg'
or name(.) = 'arg.sloppy'
or name(.) = 'arg.rpt'
or name(.) = 'arg.rpc'
or name(.) = 'arg.in'
or name(.) = 'mod'
or name(.) = 'sbj'
or name(.) = 'obj'
or name(.) = 'obj.rcp'
or name(.) = 'obj.in'
or name(.) = 'obj.sup'
or name(.) = 'obj.rpt'
or name(.) = 'obj.msr'
or name(.) = 'obj.met'
or name(.) = 'obj.loc'
or name(.) = 'obj.ql'
or name(.) = 'obj.mt'
or name(.) = 'obj.loc.msr'
or name(.) = 'obj.ctl'
or name(.) = 'iob'
or name(.) = 'iob.in'
or name(.) = 'ctl.obj'
or name(.) = 'ctl.iob'
or name(.) = 'ctl.agt'
or name(.) = 'ctl.gol'
or name(.) = 'ctl.src'
or name(.) = 'ctl.exp'
or name(.) = 'ctl.res'
or name(.) = 'ctl.cap'
or name(.) = 'ctl.aen'
or name(.) = 'ctl.smr'
or name(.) = 'ctl.res.mt'
or name(.) = 'ctl.pbj'
or name(.) = 'ctl.obl'
or name(.) = 'ctl.obj.rcp'
or name(.) = 'ctl.ioc'
or name(.) = 'ctl.ilb'
or name(.) = 'ctl.cnt'
or name(.) = 'ctl.agt.rpt'
or name(.) = 'plg'
or name(.) = 'agt'
or name(.) = 'agt.rcp'
or name(.) = 'agt.rpt'
or name(.) = 'agt.sit'
or name(.) = 'agt.sub'
or name(.) = 'agt.sup'
or name(.) = 'agt.spt'
or name(.) = 'agt.msr'
or name(.) = 'agt.met'
or name(.) = 'agt.jnt'
or name(.) = 'agt.in'
or name(.) = 'cap'
or name(.) = 'aen'
or name(.) = 'aen.rcp'
or name(.) = 'aen.sub'
or name(.) = 'rpt'
or name(.) = 'src'
or name(.) = 'src.loc'
or name(.) = 'gol'
or name(.) = 'gol.ilc'
or name(.) = 'gol.obj'
or name(.) = 'gol.loc'
or name(.) = 'gol.sit'
or name(.) = 'res'
or name(.) = 'res.mt'
or name(.) = 'res.msr'
or name(.) = 'mat'
or name(.) = 'ben'
or name(.) = 'exp'
or name(.) = 'exp.rpt'
or name(.) = 'exp.rcp'
or name(.) = 'exp.met'
or name(.) = 'jnt'
or name(.) = 'pos'
or name(.) = 'ela'
or name(.) = 'eg'
or name(.) = 'cnt'
or name(.) = 'tnc'
or name(.) = 'cau'
or name(.) = 'pur'
or name(.) = 'cnd'
or name(.) = 'sub'
or name(.) = 'sup'
or name(.) = 'sup.mt'
or name(.) = 'tmx'
or name(.) = 'tmx.mob'
or name(.) = 'tim'
or name(.) = 'spx'
or name(.) = 'spx.sup'
or name(.) = 'spx.sub'
or name(.) = 'spx.mob'
or name(.) = 'loc'
or name(.) = 'ilc'
or name(.) = 'ilc.gol'
or name(.) = 'via'
or name(.) = 'dir'
or name(.) = 'opp'
or name(.) = 'int'
or name(.) = 'fin'
or name(.) = 'stx.mob'
or name(.) = 'sit'
or name(.) = 'sit.sup'
or name(.) = 'txx.sub'
or name(.) = 'in'
or name(.) = 'in.sloppy'
or name(.) = 'ni'
or name(.) = 'ccm'
or name(.) = 'met'
or name(.) = 'cmp'
or name(.) = 'sim'
or name(.) = 'bas'
or name(.) = 'cev'
or name(.) = 'who'
or name(.) = 'whm'
or name(.) = 'mns'
or name(.) = 'mns.sup'
or name(.) = 'msr'
or name(.) = 'mob'
or name(.) = 'mob.in'
or name(.) = 'ql'
or name(.) = 'sbm'
or name(.) = 'sbm.sloppy'
or name(.) = 'sbm.mt'
or name(.) = 'uni'
or name(.) = 'mkr'
or name(.) = 'adr'
or name(.) = 'age'
or name(.) = 'utr'
or name(.) = 'smr'
or name(.) = 'otr'
">
      <xsl:value-of select="name(.)"/>
      <xsl:text>,</xsl:text>
      <xsl:value-of select="."/>
      <xsl:text>||</xsl:text>
    </xsl:if>
  </xsl:for-each>
</xsl:template>

</xsl:stylesheet>
